# Generated by Django 3.1.7 on 2021-06-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210624_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('notation', models.IntegerField(blank=True, default=0, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('mode_paiement', models.CharField(blank=True, max_length=255, null=True)),
                ('taxe', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_paye', models.BooleanField(default=False)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('is_delivre', models.BooleanField(default=False)),
                ('delivre_le', models.DateTimeField(blank=True, null=True)),
                ('ajouter_le', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CmdeItem',
            fields=[
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AddLivraison',
            fields=[
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postale', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_livraison', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.commande')),
            ],
        ),
    ]
